### ISSUE TITLE
Package for Fedora

### ISSUE THREAD

**Issue by atrauzzi** [TheAlexDev23/power-options#2] opened 2024-09-15 10:18 UTC
Would love to try this out, but I'm probably only going to once it's ready on Fedora. 

Keep us all posted here and once this ticket closes, anyone subscribed will get the notification!

**Comment by meduk0** [comment] 2024-09-15 17:34
you can make some changes to the install script to work with fedora (it won't be that hard mostly just change some pkgs names ) as the installer gonna use cargo anyway .
I have not used fedora (rpm in general for years ) but it would be easy to get it done (if you are familiar with how packaging works) or just wait until this project get bigger enough to be well know and provide the rpm you need

**Comment by TheAlexDev23** [comment] 2024-09-15 17:40
What part of the gtk install script will not work under fedora? It seems distro-independant to me.

**Comment by meduk0** [comment] 2024-09-15 18:08
@TheAlexDev23 it usually don't as different distros tend to have different packages names that is why it is hard to port some software to arch or any  distro (and usually left for the community to do that ) . i recommand setting up a fedora container and trying (it is ez thx to distrobox )

**Comment by TheAlexDev23** [comment] 2024-09-15 18:12
@meduk0 I don’t think I understand what you’re trying to say. The gtk install script doesn’t reference any programs other than cargo, what packages with a potential different name are you talking about?

**Comment by TheAlexDev23** [comment] 2024-09-15 20:46
@atrauzzi yeah, of course. The hard part is automating the process through CI. But I will definetly look for ways to do that when the backlog clears up from higher priority issues.

**Comment by dagimg-dot** [comment] 2024-09-16 08:51
You can try it now after installing the dependencies. It worked for me

```sh
sudo dnf install acpid graphene-devel gtk4-devel libadwaita-devel
```

then

```sh
./install-gtk.sh
```

**Comment by lpuv** [comment] 2024-09-17 02:25
Hi all, I have made a COPR repository for this.
Let me know if it works for you!
https://copr.fedorainfracloud.org/coprs/leo/power-options/

Please note that this is not following the official rust guidelines for *official* packaging so it can be distributed by COPR, but not added to official fedora repos until all rust dependencies are properly packaged.

**Comment by lpuv** [comment] 2024-09-17 15:34
@atrauzzi what i mean by that is it cannot be installed into official Fedora repos. It can be packaged on COPR no problem.

**Comment by meduk0** [comment] 2024-09-17 15:44
maybe it will be in the official one if the project become well known

**Comment by lpuv** [comment] 2024-09-17 17:44
@meduk0 the issue is that because of how rust-based packages are packaged in fedora they require every single dependency to also be officially packaged before it can be packaged. That is what takes the most time, if all the dependencies were packaged I could do it without any issues.
See https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_rust_applications_non_crates_io_crates

**Comment by lpuv** [comment] 2024-09-18 06:15
@TheAlexDev23 
Thanks to COPR, it's really simple.
```
sudo dnf copr enable leo/power-options 
sudo dnf install power-options
```

**Comment by TheAlexDev23** [comment] 2024-09-18 06:17
That will also include dependencies right?

**Comment by lpuv** [comment] 2024-09-18 14:20
Yes, of course!

**Comment by TheAlexDev23** [comment] 2024-09-18 15:33
Thanks! Updating the readme now.

**Comment by lpuv** [comment] 2024-09-18 17:40
Actually, looks like there are only a few dependencies that are not packaged. I'll work on that but in the meantime COPR works

**Comment by TheAlexDev23** [comment] 2024-10-02 14:39
@theuser18 If you've already rebooted since install and this issue persists, its likely due to the daemon panicking in the background. Send the output of `journalctl -u power-options` and consider opening a separate issue as its likely not related to the fedora package.

**Comment by theuser18** [comment] 2024-10-02 18:02
@lpuv Have you seen #24?

**Comment by lpuv** [comment] 2024-10-24 20:24
Apologies, this completely flew under the radar. Will get to it

> @lpuv Have you seen #24?

**Closed** 2024-11-19 18:18 UTC
