### ISSUE TITLE
Daemon Panic After Initial Install

### ISSUE THREAD

**Issue by theuser18** [TheAlexDev23/power-options#24] opened 2024-10-02 15:25 UTC
I am using the Framework laptop 11th gen Intel i5 running a fully updated Fedora 40. 

I get the following error when trying to launch the program, even after multiple reboots.

```
Unexpected error occurred 
                    
- Please make sure that the power-options daemon is running.
                    
- If this is your first time running the app since installing you might need to reboot.
                    
Full panic message:
panicked at crates/frontend-gtk/src/communications/daemon_control.rs:39:56:
called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name is not activatable"), Msg { type: Error, serial: 4294967295, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 2, body: Signature("s"), fds: [] })
```

The output of `journalctl -u power-options` is `-- No entries --`

**Comment by TheAlexDev23** [comment] 2024-10-02 15:30
That's really weird, it should have some entries. What's the output of `sysremctl status power-options`?

**Comment by theuser18** [comment] 2024-10-02 15:38
Do you mean `systemctl status power-options`?

```
○ power-options.service - power-options daemon
     Loaded: loaded (/usr/lib/systemd/system/power-options.service; disabled; p>
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
```

**Comment by TheAlexDev23** [comment] 2024-10-02 15:42
Yeah sorry for the typo. 

It seems like the service was not started. Could you start it/enable it manually with systemctl? Does it output anything then?

**Comment by theuser18** [comment] 2024-10-02 15:49
```
$ systemctl start power-options
$ systemctl status power-options
× power-options.service - power-options daemon
     Loaded: loaded (/usr/lib/systemd/system/power-options.service; disabled; p>
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Wed 2024-10-02 11:47:17 EDT; 8s a>
   Duration: 9ms
    Process: 9664 ExecStart=/usr/bin/power-daemon-mgr daemon (code=exited, stat>
   Main PID: 9664 (code=exited, status=101)
        CPU: 8ms

Oct 02 11:47:17 fedora systemd[1]: Started power-options.service - power-option>
Oct 02 11:47:17 fedora power-daemon-mgr[9664]: thread 'main' panicked at crates>
Oct 02 11:47:17 fedora power-daemon-mgr[9664]: Could not read config: Os { code>
Oct 02 11:47:17 fedora power-daemon-mgr[9664]: note: run with `RUST_BACKTRACE=1>
Oct 02 11:47:17 fedora systemd[1]: power-options.service: Main process exited, >
Oct 02 11:47:17 fedora systemd[1]: power-options.service: Failed with result 'e>
lines 1-16/16 (END)...skipping...
× power-options.service - power-options daemon
     Loaded: loaded (/usr/lib/systemd/system/power-options.service; disabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Wed 2024-10-02 11:47:17 EDT; 8s ago
   Duration: 9ms
    Process: 9664 ExecStart=/usr/bin/power-daemon-mgr daemon (code=exited, status=101)
   Main PID: 9664 (code=exited, status=101)
        CPU: 8ms

Oct 02 11:47:17 fedora systemd[1]: Started power-options.service - power-options daemon.
Oct 02 11:47:17 fedora power-daemon-mgr[9664]: thread 'main' panicked at crates/power-daemon/src/lib.rs:366:44:
Oct 02 11:47:17 fedora power-daemon-mgr[9664]: Could not read config: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Oct 02 11:47:17 fedora power-daemon-mgr[9664]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Oct 02 11:47:17 fedora systemd[1]: power-options.service: Main process exited, code=exited, status=101/n/a
Oct 02 11:47:17 fedora systemd[1]: power-options.service: Failed with result 'exit-code'.
```

**Comment by TheAlexDev23** [comment] 2024-10-02 15:54
Oh yeah, this happens when power options has not been initialized. The copr package is community made so I do not have control over it, but what it should have ran the following after installing the package `sudo power-daemon-mgr setup` and then restart power-options. Basically what [this script](https://github.com/TheAlexDev23/power-options/blob/main/scripts/setup.sh) does

**Comment by TheAlexDev23** [comment] 2024-10-02 18:03
Temporarily of course, you can still run the commands within setup.sh until the package gets fixed.

**Comment by theuser18** [comment] 2024-10-02 19:33
> Temporarily of course, you can still run the commands within setup.sh until the package gets fixed.

Would you mind sharing how to do that?

**Comment by TheAlexDev23** [comment] 2024-10-02 19:36
Just copy paste the commands in [setup.sh](https://github.com/TheAlexDev23/power-options/blob/main/scripts/setup.sh) into a terminal and you should be good. Especially given that this has to only be run once for the first time power-options is installed any further updates will not require this.

**Comment by lpuv** [comment] 2024-10-24 20:24
Apologies, this completely flew under the radar. Will get to it

**Comment by lpuv** [comment] 2024-10-24 20:30
@TheAlexDev23 Unfortunately according to [Fedora's policies](https://docs.fedoraproject.org/en-US/packaging-guidelines/DefaultServices/) the package is not allowed to enable itself. I can still package it to do that, but then it would not go into official repos ever. The recommended way would be to simply add `sudo systemctl enable --now power-options` to the installation instructions after installing the RPM. Let me know what oyu think!

**Comment by TheAlexDev23** [comment] 2024-10-24 21:10
@lpuv, how much does Fedora restrict the execution of setup commands? `power-daemon-mgr setup` only generates config files. The settings are only applied by the daemon which obviously only runs if started by the user. Altough it does gather system info, which might have restrictions? I've added the custom sysroot parameter, tell me if other parameters are required, but I assume /etc (which is the only folder the setup command writes to) does not have the ambiguity problem that /bin, /usr/bin or /usr/local/bin does.

**Comment by lpuv** [comment] 2024-10-24 22:39
After thinking about it, the issue is that some of the setup (generating config) would need to be run by the user anyway as it could not be run on Fedora's build servers.

**Comment by lpuv** [comment] 2024-10-25 17:30
@TheAlexDev23 Let me work on it.

**Comment by lpuv** [comment] 2024-10-25 23:52
@TheAlexDev23 It seems to work, though I am wondering something. Does the setup script require a display connection?

**Comment by TheAlexDev23** [comment] 2024-10-26 11:11
Yes, do you think it's better to move the prompt to the CLI?

**Comment by lpuv** [comment] 2024-10-26 21:22
The issue is the script will not have access to a display during install. It seems to result in "default" profiles being the only ones created.

**Comment by TheAlexDev23** [comment] 2024-10-26 22:23
Yeah that's the fallback behavior when something out of control occurs, it's meant to be as less destructive as possible. I'll make it cli only.

**Comment by lpuv** [comment] 2024-10-29 19:59
@TheAlexDev23 Thanks! Should work as intended now. I'll update to v1.2.1

**Comment by TheAlexDev23** [comment] 2024-10-29 20:11
Just made a new release, it should have the latest version of the CLI util.

**Comment by lpuv** [comment] 2024-10-29 21:02
Perfect. I'll update now.

**Comment by TheAlexDev23** [comment] 2024-11-19 18:17
Forgot to close this. Should be fixed by now.

**Closed by TheAlexDev23** 2024-11-19 18:17 UTC
